/**
 * Appendix Section - Technical details and metadata
 */

import { createMetadataTable } from '../../formatters/table-formatter.js';

export function generateAppendix(analysisResult) {
  const {
    analyzed_at,
    analysis_cost,
    analysis_time,
    crawl_metadata,
    seo_analysis_model,
    content_analysis_model,
    desktop_visual_model,
    mobile_visual_model,
    social_analysis_model,
    accessibility_analysis_model
  } = analysisResult;

  let output = `# Appendix: Technical Details\n\n`;

  // Analysis Metadata
  output += `## 📊 Analysis Metadata\n\n`;

  const metadata = {
    analyzed_at,
    analysis_cost,
    analysis_time,
    pages_crawled: crawl_metadata?.pages_crawled
  };

  // Collect AI models used
  const aiModels = [];
  if (desktop_visual_model) aiModels.push(desktop_visual_model);
  if (mobile_visual_model && mobile_visual_model !== desktop_visual_model) aiModels.push(mobile_visual_model);
  if (seo_analysis_model) aiModels.push(seo_analysis_model);
  if (content_analysis_model && content_analysis_model !== seo_analysis_model) aiModels.push(content_analysis_model);
  if (social_analysis_model && !aiModels.includes(social_analysis_model)) aiModels.push(social_analysis_model);
  if (accessibility_analysis_model && !aiModels.includes(accessibility_analysis_model)) aiModels.push(accessibility_analysis_model);

  metadata.ai_models = [...new Set(aiModels)]; // Remove duplicates

  output += createMetadataTable(metadata);

  // AI Models and Prompts Used
  if (aiModels.length > 0) {
    output += `## 🤖 Analysis Configuration\n\n`;
    output += `This analysis was powered by AI models selected for this project:\n\n`;

    const modelMapping = {
      desktop_visual_model: 'Desktop Visual Analysis',
      mobile_visual_model: 'Mobile Visual Analysis',
      seo_analysis_model: 'SEO Analysis',
      content_analysis_model: 'Content Analysis',
      social_analysis_model: 'Social Media Analysis',
      accessibility_analysis_model: 'Accessibility Analysis'
    };

    output += `| Module | Model Used |\n`;
    output += `|--------|------------|\n`;

    Object.entries(modelMapping).forEach(([key, label]) => {
      if (analysisResult[key]) {
        output += `| ${label} | ${analysisResult[key]} |\n`;
      }
    });

    output += '\n';

    // Prompts info (if available)
    if (analysisResult.prompts_used || analysisResult._raw?.prompts) {
      output += `### Prompts Used\n\n`;
      output += `Custom AI prompts were configured for this project to ensure consistent analysis quality.\n\n`;
    }
  }

  // Report Generation Info
  output += `## 📄 Report Information\n\n`;
  output += `This report was automatically generated by the MaxantAgency Analysis Engine.\n\n`;
  output += `**Report Format:** Markdown\n\n`;
  output += `**Generated:** ${new Date().toLocaleString()}\n\n`;

  output += `---\n\n`;
  output += `_End of Report_\n`;

  return output;
}
