-- Migration: Add reports table for storing website audit reports
-- Created: 2025-01-21
-- Description: Tracks generated website audit reports stored in Supabase Storage

-- Create reports table
CREATE TABLE IF NOT EXISTS reports (
  -- Primary key
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Foreign keys
  lead_id uuid REFERENCES leads(id) ON DELETE CASCADE,
  project_id uuid REFERENCES projects(id) ON DELETE SET NULL,

  -- Report metadata
  report_type text NOT NULL DEFAULT 'website_audit',
  format text NOT NULL DEFAULT 'markdown',

  -- Storage info
  storage_path text NOT NULL,
  storage_bucket text NOT NULL DEFAULT 'reports',
  file_size_bytes bigint,

  -- Report content metadata
  company_name text NOT NULL,
  website_url text NOT NULL,

  -- Scores snapshot (for quick filtering)
  overall_score integer,
  website_grade text,

  -- Report configuration
  config jsonb DEFAULT '{}'::jsonb,

  -- Status tracking
  status text NOT NULL DEFAULT 'completed',
  error_message text,

  -- Analytics
  download_count integer DEFAULT 0,
  last_downloaded_at timestamptz,

  -- Timestamps
  generated_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_reports_lead_id ON reports(lead_id);
CREATE INDEX IF NOT EXISTS idx_reports_project_id ON reports(project_id);
CREATE INDEX IF NOT EXISTS idx_reports_status ON reports(status);
CREATE INDEX IF NOT EXISTS idx_reports_format ON reports(format);
CREATE INDEX IF NOT EXISTS idx_reports_generated_at ON reports(generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_reports_company_name ON reports(company_name);
CREATE INDEX IF NOT EXISTS idx_reports_storage_path ON reports(storage_path);

-- Constraints
ALTER TABLE reports ADD CONSTRAINT chk_reports_format
  CHECK (format IN ('markdown', 'pdf', 'html', 'json'));

ALTER TABLE reports ADD CONSTRAINT chk_reports_status
  CHECK (status IN ('generating', 'completed', 'failed'));

ALTER TABLE reports ADD CONSTRAINT chk_reports_file_size_positive
  CHECK (file_size_bytes IS NULL OR file_size_bytes >= 0);

ALTER TABLE reports ADD CONSTRAINT chk_reports_download_count_positive
  CHECK (download_count >= 0);

-- Comments for documentation
COMMENT ON TABLE reports IS 'Website audit reports generated by Analysis Engine, stored in Supabase Storage';
COMMENT ON COLUMN reports.lead_id IS 'Reference to the analyzed lead';
COMMENT ON COLUMN reports.project_id IS 'Reference to the project this report belongs to';
COMMENT ON COLUMN reports.report_type IS 'Type of report (website_audit, competitive_analysis, etc.)';
COMMENT ON COLUMN reports.format IS 'Report format (markdown, pdf, html, json)';
COMMENT ON COLUMN reports.storage_path IS 'Full path to file in Supabase Storage (e.g., reports/2025/01/lead-abc123.md)';
COMMENT ON COLUMN reports.storage_bucket IS 'Supabase Storage bucket name';
COMMENT ON COLUMN reports.file_size_bytes IS 'File size in bytes';
COMMENT ON COLUMN reports.config IS 'Report generation configuration (sections included, theme, etc.)';
COMMENT ON COLUMN reports.status IS 'Report generation status (generating, completed, failed)';
COMMENT ON COLUMN reports.download_count IS 'Number of times report has been downloaded';

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_reports_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-update updated_at
CREATE TRIGGER trigger_reports_updated_at
  BEFORE UPDATE ON reports
  FOR EACH ROW
  EXECUTE FUNCTION update_reports_updated_at();

-- Create Supabase Storage bucket (manual step in Supabase dashboard or via SQL)
-- Run this in Supabase SQL editor:
-- INSERT INTO storage.buckets (id, name, public)
-- VALUES ('reports', 'reports', false)
-- ON CONFLICT (id) DO NOTHING;

-- Storage policy for authenticated access (manual step)
-- Run this in Supabase SQL editor:
-- CREATE POLICY "Authenticated users can read reports"
-- ON storage.objects FOR SELECT
-- TO authenticated
-- USING (bucket_id = 'reports');

-- CREATE POLICY "Service role can insert reports"
-- ON storage.objects FOR INSERT
-- TO service_role
-- WITH CHECK (bucket_id = 'reports');

COMMENT ON TABLE reports IS '
Website audit reports table - stores metadata for reports generated by Analysis Engine.

Usage:
1. Analysis Engine generates a Markdown report
2. Uploads report to Supabase Storage (bucket: reports)
3. Inserts metadata record into this table with storage_path
4. UI fetches report metadata and downloads from Storage

Storage bucket setup (run manually in Supabase):
- Bucket name: reports
- Public: false (requires authentication)
- File path pattern: reports/{year}/{month}/{lead_id}-{timestamp}.md
';